### ISSUE TITLE
Getting error "Unable to fetch data: math domain error" when trying to set up second fan

### ISSUE THREAD

**Issue by JonasLundin** [angoyd/freshintelliventHacs#41]
Hi,

First of all, thanks for a great integration! 

However I have struck a problem. I have two SKY fans, one of them work flawlessly, but the second one will setup correctly, but immediately I get this error: 

![image](https://github.com/user-attachments/assets/1d1835eb-6419-4eeb-9faa-a91b5f8fd047)

I cannot see anything weird in logs when I tried to download the debug logs either... 

I have tried re-installing the integration but to no awail... Any ideas?

**Comment by JonasLundin** [comment]
This was a proximity issue, moving my bluetooth proxy closer during pairing solved the problem.

**Comment by nadizan** [comment]
I installed my Intellivent SKY last week. I got this same error now when trying to initialize it now, "failed setup: will retry: Unable to fetch data: math domain error". 

Prior to this: I got the sensor to sporadically give back some data last week, got maybe a 1 hours of data per day spread during the day - terrible coverage and impossible to update Fan data from HA since it was offline. Before I re-wiped the integration and reinstalled it, I also noted that the humidity had a baseline of - (negative) percentage, and the temperature was reported between 8-16*C, which is around 10 degrees off. The math in converting the sensor data seems way off.

I've tried all different versions now with no luck in getting it integrated. I'm not on the 0.3.0-rc.4 which gives the above-mentioned error code. Firmware version of the fan = 02.03.

Also, the signal strength from the logs seem to be pretty good. I can't see that the error is related to signal strength. I also see that the Intellivent SKY fan is lighting up the "connection" LED every time HA tries to "configure" it. Also it cannot be the transmission that is weak from the Intellivent SKY as I can move +10 meters further with my phone and still get readings from the fan.

Any help would be much appreciated, thanks.

**Comment by LaStrada** [comment]
I have
```
Firmware: 01.01
Hardware: 01.02
```
so it might be some differences in the calculations, data format etc.

Need to see the raw data to be able to know what's going on

**Comment by nadizan** [comment]
That makes sense. I was trying to look for any information on what versions this integration supported.

Sure, how can I provide the raw data from the sensor? I'm happy to help out and do some investigations myself as well.

Also, do you know if it's possible to backroll the firmware somehow?

**Comment by nadizan** [comment]
I've done some investigations, it seems like the humidity data should not be "log", since the problem is that I get drop-outs whenever my sensor value for %Humidity creeps to ~(-23%), which is log(1/10)*10. So it seems that maybe given the Firmware version I have I should not logarithmize the humidity value?

**Comment by nadizan** [comment]
Seems like there is an independent integration here that resolves my issues: https://github.com/eriknn/ha-pax_ble. Fresh Intellivent SKY is the same product as "Vent-Axia Svensa". I just got that integration to work (including data from VOC). However that HACS integration lack some of the functions integrated here that could be added there perhaps, e.g. installation of the fan. @LaStrada @angoyd
